// ── MOCK DATA ──
const NOW = Date.now();
const H = 3600000; // 1 hour in ms

window.TRATO_DATA = {
  user: {
    name: 'Royer Hernandez',
    initials: 'RH',
    rating: 4.8,
    sales: 12,
    bids: 34,
    verified: true,
    balance: 0,
  },

  auctions: [
    {
      id: 1,
      title: 'Esmeralda Natural 2.3ct — Certificada',
      category: 'joyeria',
      categoryLabel: 'Joyería',
      emoji: '💎',
      gradient: 'linear-gradient(135deg, #0d0a2e 0%, #1a1060 100%)',
      imgUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80',
      seller: { name: 'Maru Joyería', initials: 'MJ', rating: 4.9, sales: 847, verified: true },
      description: 'Hermosa esmeralda natural colombiana de 2.3 quilates. Color verde intenso, excelente transparencia y brillo. Origen: Muzo, Boyacá. Ideal para montaje en joya de lujo.',
      startPrice: 850000,
      currentPrice: 1250000,
      minIncrement: 50000,
      endsAt: NOW + 1.8 * H,
      badge: 'ending',
      badgeLabel: 'Termina pronto',
      bids: [
        { user: 'Carlos M.', initials: 'CM', amount: 1250000, time: 'hace 3 min', top: true },
        { user: 'Ana G.', initials: 'AG', amount: 1200000, time: 'hace 8 min' },
        { user: 'Pedro L.', initials: 'PL', amount: 1150000, time: 'hace 15 min' },
        { user: 'María S.', initials: 'MS', amount: 1100000, time: 'hace 22 min' },
        { user: 'Jorge R.', initials: 'JR', amount: 1050000, time: 'hace 35 min' },
      ],
      totalBids: 23,
      watchers: 156,
      condition: 'Natural sin tratamiento',
      location: 'Bogotá D.C.',
    },
    {
      id: 2,
      title: 'Reloj Seiko Automático SPB143 — Caja completa',
      category: 'relojes',
      categoryLabel: 'Relojes',
      emoji: '⌚',
      gradient: 'linear-gradient(135deg, #0d1a2e 0%, #102040 100%)',
      imgUrl: 'https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?w=600&q=80',
      seller: { name: 'Tiempo & Estilo', initials: 'TE', rating: 4.7, sales: 203, verified: true },
      description: 'Seiko Prospex SPB143 automático. Movimiento calibre 6R35, reserva de marcha 70h. Cristal zafiro, resistencia al agua 200m. Caja completa con garantía.',
      startPrice: 1200000,
      currentPrice: 1750000,
      minIncrement: 50000,
      endsAt: NOW + 5.4 * H,
      badge: 'new',
      badgeLabel: 'Nuevo',
      bids: [
        { user: 'Andrés P.', initials: 'AP', amount: 1750000, time: 'hace 1 min', top: true },
        { user: 'Camila R.', initials: 'CR', amount: 1700000, time: 'hace 12 min' },
        { user: 'Luis F.', initials: 'LF', amount: 1650000, time: 'hace 28 min' },
        { user: 'Sofía M.', initials: 'SM', amount: 1600000, time: 'hace 45 min' },
        { user: 'Diego A.', initials: 'DA', amount: 1500000, time: 'hace 1h' },
      ],
      totalBids: 17,
      watchers: 89,
      condition: 'Como nuevo',
      location: 'Medellín',
    },
    {
      id: 3,
      title: 'iPhone 15 Pro 256GB Titanio Natural',
      category: 'tecnologia',
      categoryLabel: 'Tecnología',
      emoji: '📱',
      gradient: 'linear-gradient(135deg, #0d1a0d 0%, #102010 100%)',
      imgUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80',
      seller: { name: 'TechStore CO', initials: 'TC', rating: 4.6, sales: 1240, verified: true },
      description: 'iPhone 15 Pro 256GB color Titanio Natural. Chip A17 Pro, cámara 48MP con zoom 5x. Sin rayones, batería al 96%. Desbloqueado para cualquier operador.',
      startPrice: 3200000,
      currentPrice: 3850000,
      minIncrement: 100000,
      endsAt: NOW + 26 * H,
      badge: 'hot',
      badgeLabel: '🔥 Popular',
      bids: [
        { user: 'Valentina G.', initials: 'VG', amount: 3850000, time: 'hace 5 min', top: true },
        { user: 'Sebastián C.', initials: 'SC', amount: 3750000, time: 'hace 20 min' },
        { user: 'Isabella M.', initials: 'IM', amount: 3650000, time: 'hace 40 min' },
        { user: 'Nicolás R.', initials: 'NR', amount: 3550000, time: 'hace 1h 10m' },
        { user: 'Mariana T.', initials: 'MT', amount: 3400000, time: 'hace 2h' },
      ],
      totalBids: 41,
      watchers: 312,
      condition: 'Usado - Excelente',
      location: 'Bogotá D.C.',
    },
    {
      id: 4,
      title: 'Collar Oro 18K con Esmeralda Central',
      category: 'joyeria',
      categoryLabel: 'Joyería',
      emoji: '📿',
      gradient: 'linear-gradient(135deg, #2a1a00 0%, #4a2c00 100%)',
      imgUrl: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80',
      seller: { name: 'Joyería Candelaria', initials: 'JC', rating: 5.0, sales: 423, verified: true },
      description: 'Collar artesanal en oro amarillo 18K con esmeralda central de 1.8ct y diamantes de 0.5ct total. Diseño exclusivo, elaborado por joyeros de La Candelaria. Estuche de regalo incluido.',
      startPrice: 4500000,
      currentPrice: 5200000,
      minIncrement: 200000,
      endsAt: NOW + 71 * H,
      badge: null,
      bids: [
        { user: 'Patricia V.', initials: 'PV', amount: 5200000, time: 'hace 30 min', top: true },
        { user: 'Hernán M.', initials: 'HM', amount: 5000000, time: 'hace 2h' },
        { user: 'Claudia P.', initials: 'CP', amount: 4800000, time: 'hace 4h' },
      ],
      totalBids: 8,
      watchers: 67,
      condition: 'Nuevo',
      location: 'Bogotá — La Candelaria',
    },
    {
      id: 5,
      title: 'Nike Air Jordan 1 Retro High OG — Talla 42',
      category: 'calzado',
      categoryLabel: 'Calzado',
      emoji: '👟',
      gradient: 'linear-gradient(135deg, #1a0808 0%, #300d0d 100%)',
      imgUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80',
      seller: { name: 'Sneakers Bogotá', initials: 'SB', rating: 4.8, sales: 334, verified: false },
      description: 'Air Jordan 1 Retro High OG "Chicago" talla 42. Zapatos originales Nike, nunca usados, etiqueta del precio. Caja original completa. StockX verificado.',
      startPrice: 450000,
      currentPrice: 680000,
      minIncrement: 20000,
      endsAt: NOW + 4.2 * H,
      badge: 'ending',
      badgeLabel: 'Termina pronto',
      bids: [
        { user: 'Felipe B.', initials: 'FB', amount: 680000, time: 'hace 2 min', top: true },
        { user: 'Alejandra S.', initials: 'AS', amount: 660000, time: 'hace 10 min' },
        { user: 'Daniel F.', initials: 'DF', amount: 640000, time: 'hace 25 min' },
        { user: 'Juliana O.', initials: 'JO', amount: 620000, time: 'hace 38 min' },
      ],
      totalBids: 19,
      watchers: 201,
      condition: 'Nuevo sin usar',
      location: 'Bogotá D.C.',
    },
    {
      id: 6,
      title: 'MacBook Pro M3 Pro 14" 18GB/512GB',
      category: 'tecnologia',
      categoryLabel: 'Tecnología',
      emoji: '💻',
      gradient: 'linear-gradient(135deg, #0a0a14 0%, #12122a 100%)',
      imgUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80',
      seller: { name: 'Apple Resellers', initials: 'AR', rating: 4.9, sales: 560, verified: true },
      description: 'MacBook Pro 14 pulgadas con chip M3 Pro, 18GB RAM unificada, 512GB SSD. Pantalla Liquid Retina XDR. Batería al 94%. Cargador original incluido. Sin rayones.',
      startPrice: 6800000,
      currentPrice: 7400000,
      minIncrement: 200000,
      endsAt: NOW + 49 * H,
      badge: null,
      bids: [
        { user: 'Johanna C.', initials: 'JC', amount: 7400000, time: 'hace 15 min', top: true },
        { user: 'Roberto M.', initials: 'RM', amount: 7200000, time: 'hace 1h' },
        { user: 'Natalia R.', initials: 'NR', amount: 7000000, time: 'hace 3h' },
      ],
      totalBids: 9,
      watchers: 145,
      condition: 'Usado - Excelente',
      location: 'Cali',
    },
    {
      id: 7,
      title: 'Anillo Esmeralda Baguette Oro 18K',
      category: 'joyeria',
      categoryLabel: 'Joyería',
      emoji: '💍',
      gradient: 'linear-gradient(135deg, #0a1a0a 0%, #0d2a0d 100%)',
      imgUrl: 'https://images.unsplash.com/photo-1589128777073-263566ae5e4d?w=600&q=80',
      seller: { name: 'Maru Joyería', initials: 'MJ', rating: 4.9, sales: 847, verified: true },
      description: 'Elegante anillo con esmeralda corte baguette de 1.1ct en montura de oro amarillo 18K. Acabado pulido. Talla 16 (ajustable). Certificado de autenticidad incluido.',
      startPrice: 2100000,
      currentPrice: 2550000,
      minIncrement: 100000,
      endsAt: NOW + 6.3 * H,
      badge: 'hot',
      badgeLabel: '🔥 Popular',
      bids: [
        { user: 'Paola H.', initials: 'PH', amount: 2550000, time: 'hace 7 min', top: true },
        { user: 'Ricardo G.', initials: 'RG', amount: 2450000, time: 'hace 20 min' },
        { user: 'Mónica L.', initials: 'ML', amount: 2350000, time: 'hace 45 min' },
        { user: 'Esteban V.', initials: 'EV', amount: 2250000, time: 'hace 1h 20m' },
      ],
      totalBids: 14,
      watchers: 98,
      condition: 'Nuevo',
      location: 'Bogotá D.C.',
    },
    {
      id: 8,
      title: 'Sony Alpha A7IV Body — 2500 disparos',
      category: 'tecnologia',
      categoryLabel: 'Fotografía',
      emoji: '📷',
      gradient: 'linear-gradient(135deg, #141414 0%, #202020 100%)',
      imgUrl: 'https://images.unsplash.com/photo-1617957796013-1a08f0e70878?w=600&q=80',
      seller: { name: 'FotoGear CO', initials: 'FG', rating: 4.7, sales: 127, verified: true },
      description: 'Sony Alpha A7IV body (sin lente). Sensor full frame 33MP, grabación 4K 60fps, IBIS 5 ejes. Apenas 2500 disparos. Como nuevo, con cargador original y correa.',
      startPrice: 5400000,
      currentPrice: 5900000,
      minIncrement: 200000,
      endsAt: NOW + 30 * H,
      badge: 'new',
      badgeLabel: 'Nuevo',
      bids: [
        { user: 'Laura C.', initials: 'LC', amount: 5900000, time: 'hace 40 min', top: true },
        { user: 'Mauricio P.', initials: 'MP', amount: 5700000, time: 'hace 2h' },
      ],
      totalBids: 6,
      watchers: 78,
      condition: 'Usado - Como nuevo',
      location: 'Medellín',
    },
  ],

  wonAuction: {
    id: 99,
    title: 'Esmeralda Natural 2.3ct — Certificada',
    emoji: '💎',
    gradient: 'linear-gradient(135deg, #0d0a2e 0%, #1a1060 100%)',
    seller: { name: 'Maru Joyería', initials: 'MJ' },
    finalPrice: 1250000,
    myBid: 1250000,
    wonAt: new Date().toLocaleDateString('es-CO', { day: '2-digit', month: 'long', year: 'numeric' }),
    payDeadline: NOW + 24 * H,
    transactionId: 'TRT-2024-001842',
  },

  sellers: [
    {
      id: 'maru-joyeria',
      name: 'Maru Joyería',
      initials: 'MJ',
      tagline: 'Esmeraldas Colombianas · Joyería Artesanal',
      gradient: 'linear-gradient(135deg, #8B2FC9 0%, #3CBCB8 100%)',
      badges: ['✅ Identidad verificada', '💎 Esmeraldas', '🏆 Top Vendedor'],
      location: 'Bogotá, Colombia',
      memberSince: 'mar 2023',
      rating: 4.9,
      sales: 247,
      activeListings: 8,
      followers: 1200,
      deliveryRate: 98,
      verification: { cedula: true, facial: true, phone: true },
      ratingDistribution: { 5: 92, 4: 6, 3: 2, 2: 0, 1: 0 },
      bio: 'Especialistas en esmeraldas colombianas y joyería artesanal fina. Más de 15 años de experiencia en el mercado de Bogotá. Todas nuestras piedras tienen certificado de origen.',
    },
  ],

  categories: [
    { id: 'all', label: 'Todos' },
    { id: 'joyeria', label: 'Joyería' },
    { id: 'relojes', label: 'Relojes' },
    { id: 'tecnologia', label: 'Tecnología' },
    { id: 'calzado', label: 'Calzado' },
  ],

  // Format Colombian Peso
  fmt(n) {
    return new Intl.NumberFormat('es-CO', {
      style: 'currency', currency: 'COP',
      minimumFractionDigits: 0, maximumFractionDigits: 0,
    }).format(n);
  },

  // Format countdown
  countdown(endsAt) {
    const diff = endsAt - Date.now();
    if (diff <= 0) return { str: '00:00:00', state: 'expired', seconds: 0 };
    const s = Math.floor(diff / 1000);
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    const sec = s % 60;
    const pad = (n) => String(n).padStart(2, '0');
    let str, state;
    if (h >= 24) { const d = Math.floor(h / 24); str = `${d}d ${pad(h % 24)}h ${pad(m)}m`; state = 'ok'; }
    else if (h >= 1) { str = `${pad(h)}:${pad(m)}:${pad(sec)}`; state = h < 3 ? 'soon' : 'ok'; }
    else { str = `${pad(m)}:${pad(sec)}`; state = 'urgent'; }
    return { str, state, seconds: s };
  },
};
